# YOUR NAME OR TITLE OF YOUR SITE
name: Insolor

# YOUR BRAND/PERSONAL TAGLINE
tagline: "TODO: some tagline"

# YOUR/BRAND IMAGE URL
Image_URL: https://github.com/insolor.png

# CHANGE THE BACKGROUND IMAGE OF THE WEBSITE BY JUST ADDING THE IMAGE URL
Cover_Image: https://source.unsplash.com/random

# Links are moved into _data/links.yml

# YOU CAN REMOVE FOOTER COMPLETELY BY SIMPLY REMOVING EITHER THE YES OR REMOVING THE FOOTER STATEMENT BELOW COMPLETELY
footer: 'No'

# STOP EDITING HERE ---------- YOU'VE REACHED THE END OF THE CONFIGURATION

# Compress
compress_html:
  clippings: all

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - Icon

# Base URL
baseurl: /links

# Default Markdown Engine
markdown: kramdown

yandex_metrika:
  id: 48492119
